### ISSUE TITLE
add guess game

### ISSUE THREAD

**Issue by nikki332** [nikkipvt/guess#1]
add guess game small logic

[this is a link](www.youtube.com) and **this is bold**
![Screenshot 2020-09-22 at 3 57 47 PM](https://user-images.githubusercontent.com/72241135/94950278-019ae780-0500-11eb-9c9b-e971c52410e1.png)

**Comment by nikki332** [comment]
pls comment before pr

**Comment by Sai-Nikhita** [comment]
can i participate?

**Comment by nikki332** [comment]
yes u can
